---
# Role variables for credential rotation

# Target user for password rotation
target_user: root

# Default rotation tracking file
rotation_tracking_file: "/etc/credential-rotation-last"

# Backup directory for old password hashes
backup_dir: "/var/backups/credential-rotation"

# Log file locations
rotation_log_file: "{{ local_log_path }}/rotation-{{ ansible_date_time.date }}.log"
error_log_file: "{{ local_log_path }}/errors-{{ ansible_date_time.date }}.log"